// frontend/src/components/NavBar.tsx
import { Link, NavLink } from 'react-router-dom';
import { Menu, X } from 'lucide-react';
import { useState } from 'react';

export default function Navbar() {
    const [isOpen, setIsOpen] = useState(false);

    const toggleMenu = () => setIsOpen(!isOpen);

    const navLinkClass = ({ isActive }: { isActive: boolean }) =>
        `relative font-bold text-white text-lg tracking-wide transition 
        hover:after:w-full after:transition-all after:duration-300 after:absolute after:-bottom-1 after:left-0 
        after:h-[2px] after:bg-white after:w-0 ${isActive ? 'after:w-full' : ''}`;

    return (
        <nav className="bg-gradient-to-r from-blue-400 to-blue-700 shadow-md">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="flex justify-between items-center h-16">
                    {/* Logo */}
                    <div className="flex-shrink-0 text-2xl font-extrabold text-white tracking-tight shadow-sm">
                        <Link to="/" className="hover:text-gray-100">
                            Product Inventory
                        </Link>
                    </div>

                    {/* Desktop Links */}
                    <div className="hidden md:flex gap-10 items-center">
                        <NavLink to="/" end className={navLinkClass}>
                            Home
                        </NavLink>
                        <NavLink to="/products" className={navLinkClass}>
                            Products
                        </NavLink>
                        <NavLink to="/products/new" className={navLinkClass}>
                            Add Product
                        </NavLink>
                    </div>

                    {/* Mobile Menu Button */}
                    <div className="md:hidden">
                        <button onClick={toggleMenu} className="text-white focus:outline-none">
                            {isOpen ? <X size={24} /> : <Menu size={24} />}
                        </button>
                    </div>
                </div>
            </div>

            {/* Mobile Menu */}
            {isOpen && (
                <div className="md:hidden px-4 pb-4 space-y-2">
                    <NavLink to="/" end onClick={toggleMenu} className={navLinkClass}>
                        Home
                    </NavLink>
                    <NavLink to="/products" onClick={toggleMenu} className={navLinkClass}>
                        Products
                    </NavLink>
                    <NavLink to="/products/new" onClick={toggleMenu} className={navLinkClass}>
                        Add Product
                    </NavLink>
                </div>
            )}
        </nav>
    );
}

// frontend-angular/src/app/navbar/navbar.component.ts
import { Component } from '@angular/core';
import {Router, RouterLink, RouterLinkActive} from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterLinkActive, RouterLink],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css'],
})
export class NavbarComponent {
  isOpen = false;

  constructor(private router: Router) {}

  toggleMenu() {
    this.isOpen = !this.isOpen;
  }

  closeMenu() {
    this.isOpen = false;
  }

  getNavLinkClass(path: string): string {
    const isActive = this.router.url === path;
    const base = 'relative font-bold text-white text-lg tracking-wide after:absolute after:-bottom-1 after:left-0 after:h-[2px] after:bg-white';
    return isActive
      ? `${base} after:w-full`
      : `${base} after:transition-all after:duration-300 after:w-0 hover:after:w-full`;
  }
}

<nav class="bg-gradient-to-r from-blue-400 to-blue-700 shadow-md w-full">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between items-center h-16">
      <!-- Logo -->
      <div class="text-2xl font-extrabold text-white tracking-tight shadow-sm">
        <a routerLink="/" class="hover:text-gray-100">
          Product Inventory
        </a>
      </div>

      <!-- Desktop Links -->
      <div class="hidden md:flex gap-10 items-center">
        <a
          routerLink="/"
          [routerLinkActive]="'active'"
          [ngClass]="getNavLinkClass('/')"
        >
          Home
        </a>
        <a
          routerLink="/products"
          [routerLinkActive]="'active'"
          [ngClass]="getNavLinkClass('/products')"
        >
          Products
        </a>
        <a
          routerLink="/products/new"
          [routerLinkActive]="'active'"
          [ngClass]="getNavLinkClass('/products/new')"
        >
          Add Product
        </a>
      </div>

      <!-- Mobile Menu Button -->
      <div class="md:hidden">
        <button (click)="toggleMenu()" class="text-white focus:outline-none">
          <span *ngIf="!isOpen">&#9776;</span>
          <span *ngIf="isOpen">&#10005;</span>
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile Menu -->
  <div *ngIf="isOpen" class="md:hidden bg-blue-600 w-full px-2 pb-4 space-y-2">
    <a routerLink="/" (click)="closeMenu()" class="mobile-link">Home</a>
    <a routerLink="/products" (click)="closeMenu()" class="mobile-link">Products</a>
    <a routerLink="/products/new" (click)="closeMenu()" class="mobile-link">Add Product</a>
  </div>
</nav>
